blogger_blog_comment:
    resource: "@BloggerBlogBundle/Resources/config/routing/comment.yml"
    prefix:   /comment


BloggerBlogBundle_homepage:
    pattern:  /
    defaults: { _controller: BloggerBlogBundle:Page:index }
    requirements:
        _method:  GET

BloggerBlogBundle_about:
    pattern:  /about
    defaults: { _controller: BloggerBlogBundle:Page:about }
    requirements:
        _method:  GET

BloggerBlogBundle_contact:
    pattern:  /contact
    defaults: { _controller: BloggerBlogBundle:Page:contact }
    requirements:
        _method:  GET|POST

BloggerBlogBundle_blog_show : 
    pattern:   /{id}/{slug} 
    defaults: {  _controller :  BloggerBlogBundle:Blog:show } 
    requirements: 
        _method:   GET 
        id: \d+

BloggerBlogBundle_comment_create:
    pattern:  /comment/{blog_id}
    defaults: { _controller: BloggerBlogBundle:Comment:create }
    requirements:
        _method:  POST
        blog_id: \d+

blogger_blog_blog:
    resource: "@BloggerBlogBundle/Resources/config/routing/blog.yml"
    prefix:   /blog

BloggerBlogBundle_blog_tags : 
    pattern:   /tags/{tags_name} 
    defaults: {  _controller :  BloggerBlogBundle:Blog:blog_tags } 
    requirements: 
        _method:   GET
        
